# Generated by Django 3.0.3 on 2020-03-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200217_1633'),
        ('reading_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Book'),
        ),
    ]
