# Generated by Django 3.0.3 on 2020-03-19 19:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0002_language_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=150)),
                ('publisher', models.CharField(blank=True, max_length=150, null=True)),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('description', models.TextField()),
                ('category', models.TextField()),
                ('small_thumbnail', models.URLField()),
                ('thumbnail', models.URLField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
            ],
        ),
    ]
