# Generated by Django 3.0.3 on 2020-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
