# Generated by Django 3.0.2 on 2020-02-07 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='thumbmail',
            new_name='thumbnail',
        ),
    ]
