# Generated by Django 3.0.3 on 2020-05-13 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200513_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
