# Generated by Django 3.0.2 on 2020-02-17 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200207_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
