# Generated by Django 3.0.3 on 2020-03-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionTranslations',
        ),
    ]
