# Generated by Django 3.0.3 on 2020-03-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0002_delete_sessiontranslations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsession',
            old_name='length',
            new_name='duration',
        ),
    ]
