# Generated by Django 3.0.3 on 2020-03-23 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0002_readingsession_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readingsession',
            old_name='reading_list',
            new_name='library_item',
        ),
    ]
