# Generated by Django 3.0.3 on 2020-04-15 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0003_auto_20200323_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
