# Generated by Django 3.0.3 on 2020-04-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0004_readingsession_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingsession',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('E', 'Ended By User'), ('F', 'Finished')], default='N', max_length=1),
        ),
    ]
