# Generated by Django 2.2 on 2019-12-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_remove_translation_user'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tranlsations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tranlsations', to='translator.Translation'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_language', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_being_learned',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='language_being_learned', to='languages.Language'),
        ),
    ]
