# Generated by Django 2.2 on 2019-12-07 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191207_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tranlsations',
        ),
    ]
