# Generated by Django 3.0.2 on 2020-01-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_short_code'),
        ('accounts', '0003_remove_userprofile_tranlsations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_language',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='first_language', to='languages.Language'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language_being_learned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_being_learned', to='languages.Language'),
        ),
    ]
