# Generated by Django 2.2.4 on 2019-08-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language_being_learned',
        ),
    ]
