# Generated by Django 2.2.4 on 2019-08-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_short_code'),
        ('accounts', '0002_auto_20190826_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_language', to='languages.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language_being_learned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='language_being_learned', to='languages.Language'),
            preserve_default=False,
        ),
    ]
