# Generated by Django 3.0.3 on 2020-03-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0002_language_short_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.Language')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemmatizer.Mood')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=50)),
                ('tense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemmatizer.Tense')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lemmatizer.Verb')),
            ],
        ),
    ]
