# Generated by Django 3.0.3 on 2020-03-06 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_language_short_code'),
        ('lemmatizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='languages.Language'),
            preserve_default=False,
        ),
    ]
