# Generated by Django 3.0.4 on 2020-03-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmatizer', '0002_person_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='person',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
