# Generated by Django 3.0.3 on 2020-04-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20200408_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_provided',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
