# Generated by Django 3.0.3 on 2020-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_session_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
