# Generated by Django 2.2 on 2019-12-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0003_translation_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="translation", name="user",),
    ]
