# Generated by Django 3.0.3 on 2020-03-10 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_translation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
