# Generated by Django 3.0.3 on 2020-03-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reading_sessions', '0002_delete_sessiontranslations'),
        ('translator', '0006_translation_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reading_sessions.ReadingSession'),
            preserve_default=False,
        ),
    ]
